/** @file     Rte_BEA.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#include "Rte_BEA.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /Component/BEA/IB_BEA/OperationInvokedEvent_BrakeValue */

FUNC(void, BEA_CODE) RunnableEntity_BEA_Receive_func(VAR(float64, AUTOMATIC) DLBrakeValue,
                                                     VAR(float64, AUTOMATIC) DRBrakeValue,
                                                     VAR(float64, AUTOMATIC) ULBrakeValue,
                                                     VAR(float64, AUTOMATIC) URBrakeValue)
{
   /* ... */
}

