/** @file     Rte_Cfg.h
  *
  * @brief    RTE Configuration file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#ifndef RTE_CFG_H
#define RTE_CFG_H

#include <Std_Types.h>

/* BEGIN: VFB tracing definitions */
#ifndef RTE_VFB_TRACE
#define RTE_VFB_TRACE                            (0)
#endif /*RTE_VFB_TRACE*/
/* END: VFB tracing definitions */

#endif /* !RTE_CFG_H */
