/** @file     Rte_SensorSWComponent.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#ifndef RTE_SENSORSWCOMPONENT_H
#define RTE_SENSORSWCOMPONENT_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_SensorSWComponent_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if !defined(RTE_RUNNABLEAPI_RE_Sensor_Receive)
#define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_SensorSWComponent {
   uint8 _dummy;
};
typedef struct Rte_CDS_SensorSWComponent Rte_CDS_SensorSWComponent;

/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
extern CONST(struct Rte_CDS_SensorSWComponent, RTE_CONST) Rte_Inst_SensorSWComponent;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_SensorSWComponent, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#define Algo_START_SEC_CODE
#include "Algo_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, Algo_CODE) RunnableEntity_Send_func(VAR(float64, AUTOMATIC) DLWheelSpeed,
                                               VAR(float64, AUTOMATIC) DRWheelSpeed,
                                               VAR(float64, AUTOMATIC) ULWheelSpeed,
                                               VAR(float64, AUTOMATIC) URWheelSpeed,
                                               VAR(float64, AUTOMATIC) Gyro,
                                               VAR(float64, AUTOMATIC) CarSpeed,
                                               VAR(float64, AUTOMATIC) SteeringAngle);

#define Algo_STOP_SEC_CODE
#include "Algo_MemMap.h" /*lint !e537 permit multiple inclusion */
#define EcuAbstraction_START_SEC_CODE
#include "EcuAbstraction_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, EcuAbstraction_CODE) RunnableEntity_WheelSpeed_func(CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) DLWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) DRWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) ULWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) URWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) CarSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) SteeringAngle,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) Gyro);

#define EcuAbstraction_STOP_SEC_CODE
#include "EcuAbstraction_MemMap.h" /*lint !e537 permit multiple inclusion */
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
extern CONST(Rte_SelfType_Algo, RTE_DATA) Rte_Self_CPT_Algo;
extern CONST(Rte_SelfType_EcuAbstraction, RTE_DATA) Rte_Self_CPT_EcuAbstraction;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_Sensor_Receive)
/* Inline function call optimization; Rte_Call_SensorTOAlgo_RPort_ClientServerOperation_Sensor to RunnableEntity_Send_func */
#define Rte_Call_SensorTOAlgo_RPort_ClientServerOperation_Sensor( DLWheelSpeed, DRWheelSpeed, ULWheelSpeed, URWheelSpeed, Gyro, CarSpeed, SteeringAngle ) ( RunnableEntity_Send_func(DLWheelSpeed, DRWheelSpeed, ULWheelSpeed, URWheelSpeed, Gyro, CarSpeed, SteeringAngle), ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_Sensor_Receive)
/* Inline function call optimization; Rte_Call_Sensor_RPort_ClientServerOperation_Sensor to RunnableEntity_WheelSpeed_func */
#define Rte_Call_Sensor_RPort_ClientServerOperation_Sensor( DLWheelSpeed, DRWheelSpeed, ULWheelSpeed, URWheelSpeed, CarSpeed, SteeringAngle, Gyro ) ( RunnableEntity_WheelSpeed_func(DLWheelSpeed, DRWheelSpeed, ULWheelSpeed, URWheelSpeed, CarSpeed, SteeringAngle, Gyro), ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )

#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define SensorSWComponent_START_SEC_CODE
#include "SensorSWComponent_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, SensorSWComponent_CODE) RunnableEntity_WheelSpeedPlausi_Receive_func(void);
#define SensorSWComponent_STOP_SEC_CODE
#include "SensorSWComponent_MemMap.h" /*lint !e537 permit multiple inclusion */

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* RTE_SENSORSWCOMPONENT_H */
