/** @file     Rte_SensorSWConponent.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Sun Apr 24 17:41:23 2016
  */

#include "Rte_SensorSWConponent.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /Component/SensorSWConponent/IB_SensorSW/TimingEvent */

FUNC(void, SensorSWConponent_CODE) RunnableEntity_WheelSpeedPlausi_Receive_func(void)
{
   /* ... */
}

