/** @file     Rte_Cbk.h
  *
  * @brief    RTE generated COM callbacks
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#ifndef RTE_CBK_H
#define RTE_CBK_H

/* No COM Callback functions created */
#endif /* !RTE_CBK_H */
