/** @file     Rte_EcuAbstraction.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#include "Rte_EcuAbstraction.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /Component/EcuAbstraction/IB_EcuAbstraction/Brake_EVENT */

FUNC(void, EcuAbstraction_CODE) RunnableEntity_EcuAbstraction_Receive_func(VAR(float64, AUTOMATIC) DLBrakeValue,
                                                                           VAR(float64, AUTOMATIC) DRBrakeValue,
                                                                           VAR(float64, AUTOMATIC) ULBrakeValue,
                                                                           VAR(float64, AUTOMATIC) URBrakeValue)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /Component/EcuAbstraction/IB_EcuAbstraction/Send_EVENT */

FUNC(void, EcuAbstraction_CODE) RunnableEntity_WheelSpeed_func(CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) DLWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) DRWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) ULWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) URWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) CarSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) SteeringAngle,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) Gyro)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /Component/EcuAbstraction/IB_EcuAbstraction/Throttle_EVENT */

FUNC(void, EcuAbstraction_CODE) RunnableEntity_Throttle_func(VAR(float64, AUTOMATIC) Throttle)
{
   /* ... */
}

