/** @file     Rte_EcuAbstraction.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#ifndef RTE_ECUABSTRACTION_H
#define RTE_ECUABSTRACTION_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_EcuAbstraction_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if !defined(RTE_RUNNABLEAPI_RE_EcuAbstraction_Receive) && !defined(RTE_RUNNABLEAPI_RE_EcuAbstraction_ReceiveThrottle) && !defined(RTE_RUNNABLEAPI_RE_EcuAbstraction_Send)
#define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_EcuAbstraction {
   uint8 _dummy;
};
typedef struct Rte_CDS_EcuAbstraction Rte_CDS_EcuAbstraction;

/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
extern CONST(struct Rte_CDS_EcuAbstraction, RTE_CONST) Rte_Inst_EcuAbstraction;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_EcuAbstraction, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define EcuAbstraction_START_SEC_CODE
#include "EcuAbstraction_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, EcuAbstraction_CODE) RunnableEntity_EcuAbstraction_Receive_func(VAR(float64, AUTOMATIC) DLBrakeValue,
                                                                           VAR(float64, AUTOMATIC) DRBrakeValue,
                                                                           VAR(float64, AUTOMATIC) ULBrakeValue,
                                                                           VAR(float64, AUTOMATIC) URBrakeValue);
#define EcuAbstraction_STOP_SEC_CODE
#include "EcuAbstraction_MemMap.h" /*lint !e537 permit multiple inclusion */
#define EcuAbstraction_START_SEC_CODE
#include "EcuAbstraction_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, EcuAbstraction_CODE) RunnableEntity_WheelSpeed_func(CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) DLWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) DRWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) ULWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) URWheelSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) CarSpeed,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) SteeringAngle,
                                                               CONSTP2VAR(float64, AUTOMATIC, RTE_APPL_DATA) Gyro);
#define EcuAbstraction_STOP_SEC_CODE
#include "EcuAbstraction_MemMap.h" /*lint !e537 permit multiple inclusion */
#define EcuAbstraction_START_SEC_CODE
#include "EcuAbstraction_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, EcuAbstraction_CODE) RunnableEntity_Throttle_func(VAR(float64, AUTOMATIC) Throttle);
#define EcuAbstraction_STOP_SEC_CODE
#include "EcuAbstraction_MemMap.h" /*lint !e537 permit multiple inclusion */

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* RTE_ECUABSTRACTION_H */
