/** @file     Rte_SensorSWComponent.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#include "Rte_SensorSWComponent.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /Component/SensorSWComponent/IB_SensorSW/TimingEvent */

FUNC(void, SensorSWComponent_CODE) RunnableEntity_WheelSpeedPlausi_Receive_func(void)
{
   /* ... */
}

