/** @file     Rte_Const.h
  *
  * @brief    RTA-RTE related configuration constants
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#ifndef RTE_CONST_H
#define RTE_CONST_H

#define _EcuInstance_0_FlatView_SwComponentTypes_EcuInstance_0_FlatView_CPT_Algo              CPT_Algo
#define _EcuInstance_0_FlatView_SwComponentTypes_EcuInstance_0_FlatView_CPT_BEA               CPT_BEA
#define _EcuInstance_0_FlatView_SwComponentTypes_EcuInstance_0_FlatView_CPT_EEA               CPT_EEA
#define _EcuInstance_0_FlatView_SwComponentTypes_EcuInstance_0_FlatView_CPT_EcuAbstraction    CPT_EcuAbstraction
#define _EcuInstance_0_FlatView_SwComponentTypes_EcuInstance_0_FlatView_CPT_SensorSWComponent CPT_SensorSWComponent
#define RTE_CALPRM_NONE                                                                       (1)
#define RTE_MAINFUNCTION_PERIOD_US                                                            (10000)
#define RTE_MAINFUNCTION_PERIOD_NS                                                            (10000000)
#define RTE_NUM_TIMEOUT_ALARMS                                                                (0)
#define RTE_TASKS_ARRAYSIZE                                                                   (2)
#define RTE_PERIODIC_COUNTER_TICK_INTERVAL_US                                                 (100000)
#define RTE_MAX_USED_CORE_ID                                                                  (0)
#define RTE_OSAPI_AUTOSAR_R40                                                                 (1)
#define RTE_OSCFG_AUTOSAR_R40                                                                 (1)
#define RTE_VENDOR_MODE                                                                       (1)
#define RTE_MEASUREMENT_ENABLED                                                               (0)
#define RTE_NUM_TASKS                                                                         (2)
#define RTE_WOWP_EVENTS                                                                       (0)
/* Box: Rte: OS Environment begin */
/* The following OSENV_ macros are supported by this OS DLL: */
/* OSENV_UNSUPPORTED */
/* OSENV_RTAOS40 */
#if defined(OSENV_RTAOS40)
#if defined( OSENV_UNSUPPORTED )
#error "Please define exactly one of [ OSENV_RTAOS40, OSENV_UNSUPPORTED ] for OS_AUTOSAR40 DLL OS API."
#endif /* defined( OSENV_UNSUPPORTED ) */
#elif defined(OSENV_UNSUPPORTED)
#else
#error "Please define exactly one of [ OSENV_RTAOS40, OSENV_UNSUPPORTED ] for OS_AUTOSAR40 DLL OS API."
#endif
/* Box: User declared atomic BSW types: begin */
/* Box: User declared atomic BSW types: end */
/* Box: Rte: OS Environment end */
#endif /* RTE_CONST_H */
