/** @file     Rte_Algo.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#include "Rte_Algo.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /Component/Algo/IB_Algo/Sensor_EVENT */

FUNC(void, Algo_CODE) RunnableEntity_Send_func(VAR(float64, AUTOMATIC) DLWheelSpeed,
                                               VAR(float64, AUTOMATIC) DRWheelSpeed,
                                               VAR(float64, AUTOMATIC) ULWheelSpeed,
                                               VAR(float64, AUTOMATIC) URWheelSpeed,
                                               VAR(float64, AUTOMATIC) Gyro,
                                               VAR(float64, AUTOMATIC) CarSpeed,
                                               VAR(float64, AUTOMATIC) SteeringAngle)
{
   /* ... */
}

