/** @file     Rte_EEA.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.5.0  (R4.0 backend version: v7.2.5 (Build 34089))
  *           at Mon Apr 25 15:53:17 2016
  */

#include "Rte_EEA.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /Component/EEA/IB_EEA/TimingEvent_Receive */

FUNC(void, EEA_CODE) RunnableEntity_EEA_Receive_func(void)
{
   /* ... */
}

